spring.application.name=bani-backend
## Logging
### Show SQL statements in the console
logging.level.org.hibernate = debug

## Spring data source (data source auto configuration and data source properties)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= validate

api.security.token.secret=${JWT_SECRET}